config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  devise_for :users

  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'pages#home'

  resources :grids, only: [:show] do
    resources :group_chats, only: [:create]
  end

  resources :orders, only: [:create, :index] do
    resources :payments, only: [:new, :create]
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      post '/grids/:id/place_pixel', to: 'grids#place_pixel'
      get '/group_chats/:id/messages', to: 'group_chats#messages'
      post '/group_chats/:id/create_message', to: 'group_chats#create_message'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grid.rb
class Grid < ApplicationRecord
  has_many :group_chats

  validates :height, presence: true, numericality: { only_integer: true }
  validates :width, presence: true, numericality: { only_integer: true }

  before_create :fill_bits

  # Method for testing purposes, call .populate on a grid instance to populate
  # it with random coloured pixels.
  def populate
    bit_string = ""
    # For each coordinate in the grid it picks a random number from 0-15 and
    # converts it into a string of 4 bits
    (width * height).times { bit_string << "%04b" % rand(16) }
    self.pixel_bits = bit_string
    save!
  end

  # maybe convert from queue to some form of redis caching
  def update_pixel(xyc)
    batch_update if queue.length >= 100 # Will update pixel to db every x num of pixel_bits
    queue << [xyc[0], xyc[1], xyc[2]] unless xyc.include?(nil)
    save
  end

  private

  def fill_bits
    self.pixel_bits = ""
    (width * height).times { pixel_bits << "0000" }
  end

  def batch_update
    pixel_bits_will_change!
    queue.each do |xyc|
      start_index = (width * xyc[1] + xyc[0]) * 4
      pixel_bits[start_index..(start_index + 3)] = "%04b" % xyc[2]
    end
    self.queue = []
    save!
  end
end

app/models/group_chat.rb
class GroupChat < ApplicationRecord
  belongs_to :grid
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group_chat
  belongs_to :user

  after_create :broadcast_message

  private

  def broadcast_message
    ActionCable.server.broadcast("group_chat_#{group_chat.id}", author: user.username, content: content)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true, on: :create
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  has_many :messages

  # this causes "Unpermitted parameter: :username" for some reason
  validates :username, presence: true

  # Pre-generated by devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
  ## This code is recommended in the kitt tutorial but I don't think it applies to us

  # include Pundit

  # after_action :verify_authorized, except: :index
  # after_action :verify_policy_scoped, only: :index

  # rescue_from StandardError,                with: :internal_server_error
  # rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  # rescue_from ActiveRecord::RecordNotFound, with: :not_found

  # private

  # def user_not_authorized(exception)
  #   render json: {
  #     error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
  #   }, status: :unauthorized
  # end

  # def not_found(exception)
  #   render json: { error: exception.message }, status: :not_found
  # end

  # def internal_server_error(exception)
  #   if Rails.env.development?
  #     response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
  #   else
  #     response = { error: "Internal Server Error" }
  #   end
  #   render json: response, status: :internal_server_error
  # end
end

app/controllers/api/v1/grids_controller.rb
class Api::V1::GridsController < Api::V1::BaseController
  def place_pixel
    PixelUpdateJob.perform_later(grid_id: params[:id],
                                 x: params[:x],
                                 y: params[:y],
                                 color_index: params[:colorIndex])
  end
end

app/controllers/api/v1/group_chats_controller.rb
class Api::V1::GroupChatsController < Api::V1::BaseController
  def messages
    @group_chat = GroupChat.find(params[:id].to_i)
    messages = {}
    @group_chat.messages.each do |mes|
      messages[mes.id] = { content: mes.content,
                           author: mes.user.username,
                           created: mes.created_at }
    end
    render json: messages
  end

  def create_message
    Message.create!(user: current_user, group_chat_id: params[:id].to_i, content: params[:content])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def show
    @chat_room = ChatRoom.include(messages: :user).find(params[:id])
  end
end

app/controllers/grids_controller.rb
class GridsController < ApplicationController
  def show
    @grid = Grid.find(params[:id])
    @queue = @grid.queue
  end
end

app/controllers/group_chats_controller.rb
class GroupChatsController < ApplicationController
  def create
    @group_chat = GroupChat.new(group_chat_params)
    @group_chat.grid = Grid.find(params[:grid_id])
    @group_chat.save

    redirect_to grid_path(@group_chat.grid)
  end

  private

  def group_chat_params
    params.require(:group_chat).permit(:name)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:create]
  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.state = "pending"
    @order.save
    redirect_to new_order_payment_path(@order)
  end

  def show
    # @order = Order.where(user_id: current_user[:id])
  end

  def index
    #@order = Order.where(user_id: current_user[:id])
    @order = current_user.orders.where(state: 'paid')
  end

  private

  def order_params
    # make more secure when switching to simple form
    params.permit(:amount, :price)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
    @grid = Grid.last
    @orders = Order.where(user_id: current_user[:id]) if current_user
    @show = true if @orders
    @queue = @grid.queue
    render 'grids/show'
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_order

  def new
    @final_price = (@order.price * @order.amount)
    @final_display_price = @final_price / 100
  end

  def create
    @final_price = (@order.price * @order.amount)
    @final_display_price = @final_price / 100
    if current_user.stripe_id.nil?
      customer = Stripe::Customer.create(
        source: params[:stripeToken],
        email:  params[:stripeEmail],
      )
      current_user.update(stripe_id: customer.id)
    end

    charge = Stripe::Charge.create(
      customer:     customer.id, #current_user.stripe_id, # You should store this customer id and re-use it.
      amount:       @final_price,
      description:  "Payment of #{@final_display_price} EUR for #{@order.amount} pixels.",
      currency:     "eur"
    )
    @order.update(payment: charge.to_json, state: 'paid')
    current_user.update(pixel_credits: current_user.pixel_credits + @order.amount)
    flash[:notice] = "You've added #{@order.amount} pixels!"
    redirect_to '/'
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource_class
    User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/chat_rooms/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="chat-header">
        <h4> #<%= @chat_room.name  %> </h4>
      </div>
      <div class="messsages">
      	<% @chat_room.messages.each do |message| %>
      	<%= render "messages/message", message: message %>
      	<% end %>
      </div>
      <div id="create-message">
      	<%= simple_form_for [ @chat_room, Message.new ], remote: true do |f| %>
      	<%= f.input :content, label: false %>
      	<% end %>
      </div>
    </div>
  </div>
</div>
<% content_for :after_js do  %>
<% end  %>

app/views/grids/show.html.erb
<div id="stage">
  <!-- The display: none, hides the grid until it's position has been set -->
  <canvas class="uk-animation-fade"
          id="grid" height="<%= @grid.height %>"
          width="<%= @grid.width %>"
          data-pixel-bits="<%= @grid.pixel_bits %>"
          data-id="<%= @grid.id %>"
          data-queue="<%= Oj.dump(@queue) %>"
          style="display: none;"></canvas>
</div>

<div class="cols-container">
  <!-- Colors are inserted through javascript -->
</div>

<%= render 'shared/chatbox' %>

<%= render 'shared/alpha_modal' %>

<script>
  <% if !current_user %>
    UIkit.modal(document.getElementById('alpha-modal')).show();
  <% end %>

  const userCount = document.getElementById('user-count');
  const userCountM = document.getElementById('user-count-m');

  // There has to be a better place to put all this but
  // it's functional and working fine for now.

  const canvas = document.getElementById('grid');
  const ctx = canvas.getContext('2d');

  let mouseX = null;
  let mouseY = null;

  // These are the 16 colours, defined here so they are globally accessible.
  const rgbas = {0: [255, 255, 255, 255],
                1: [87, 87, 87, 255],
                2: [173, 35, 35, 255],
                3: [42, 75, 215, 255],
                4: [29, 105, 20, 255],
                5: [129, 74, 25, 255],
                6: [129, 38, 192, 255],
                7: [160, 160, 160, 255],
                8: [129, 197, 122, 255],
                9: [157, 175, 255, 255],
                10: [41, 208, 208, 255],
                11: [255, 146, 51, 255],
                12: [255, 238, 51, 255],
                13: [233, 222, 187, 255],
                14: [255, 205, 243, 255],
                15: [0, 0, 0, 255]}

  // Starting colour
  let color = 'rgb(0, 0, 0)';

  let click = null;

  let currentHover = [];

  // What is this doing?
  setTimeout(function(){
  document.querySelector("#grid").classList = "";
  document.querySelector("body").classList = "";
 }, 2000);
</script>

<%= render 'shared/dashboard' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no, maximum-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.9/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.9/js/uikit.min.js"></script>
    <meta name="HandheldFriendly" content="true" />
    <meta property="og:image" content="/assets/images/og-image.jpg" />
    <%= favicon_link_tag %>
    <link rel="icon" type="image/png" sizes="192x192" href="/assets/images/favicon.png">
    <title>PixelGrid</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="uk-animation-fade">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message <%= message.from?(current_user) ? "right" : "" %>">
  <%= image_tag message.user.avatar_url, class: "avatar" %>
  <div class="message-content"><%= message.content %></div>
</div>

app/views/messages/content.html.erb
<h1>Messages#content</h1>
<p>Find me in app/views/messages/content.html.erb</p>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
  // handle validation errors later
<% else %>
  const messagesContainer = document.querySelector('.messages');
  messagesContainer.insertAdjacentHTML('beforeend', '<%= j render "message", message: @message %>');
  const input = document.querySelector('#message_content');
  input.value = '';
  input.blur();
<% end %>

app/views/messages/new.html.erb
<div class="message-container" style="height: 200px with:200px">
  <h1>Here are the messages</h1>
</div>
<%= simple_form_for @message, remote: true do |f| %>
  <%= f.input_field :content, placeholder: "Write your message" %>
  <%= f.submit "Send!" %>
<% end %>

app/views/orders/index.html.erb
<h1>AlL YOUR ORDERS!</h1>
<hr>
<div>
  <h4>Your Orders:</h4>
  <% @order.each do |order| %>
    <h3>Order Date: <%= order.created_at %></h3>
    <h4>Amount of Pixels: <%= order.amount %></h4>
    <h4>Amount paid: <%= order.price * order.amount %></h4>
    <h4>Status: <%= order.state %></h4>
    <h4>TOTAL: <%= number_to_currency(((order.price * order.amount) / 100), :unit=>'€') %></h4>
    <hr>
  <% end %>
</div>

app/views/orders/show.html.erb
<!-- for redundancy maybe we will need it in the future, but disabled in the routes.rb -->

<h3>This is the show order page.</h3>
<hr>
<div>
  <h4>Your Orders:</h4>
  <% @order.each do |order| %>
    <h3>Order Date: <%= order.created_at %></h3>
    <h4>Amount of Pixels: <%= order.amount %></h4>
    <h4>Amount paid: <%= order.price %></h4>
  <% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/payments/new.html.erb
<%= form_tag order_payments_path(@order) do %>
  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-name="Pixels"
  data-email="<%= current_user.email %>"
  data-description="Pixels amount"
  data-amount="<%= @final_price %>"
  data-currency="eur"></script>
<% end %>

app/views/shared/_alpha_modal.html.erb
<div id="alpha-modal" uk-modal>
  <div class="uk-modal-dialog uk-modal-body">
    <button class="uk-modal-close-default" type="button" uk-close></button>
    <h2 class="uk-modal-title mb-3 border-bottom pb-2">
      Welcome to <strong>pixelGrid</strong>
    </h2>
    <p>
      You are currently viewing an <mark style="color: blue;">alpha version</mark> of the pixelGrid.<br><br>

      The website is still being developed so please be bear with us as we are improving it every day. We will be relaunching the site in early October with a partnership with a well known charity and more features that we are sure you will love. If you are interested please sign up for an account now and we will be sure to contact you when we <mark style="color: blue;">officially launch in October.</mark><br><br>

      Together, we can build the bigger picture.
    </p>
  </div>
</div>

app/views/shared/_chatbox.html.erb
<div class="uk-card uk-card-default uk-card-body" id="chatbox">

<a id="chat-exit" href="#chatbox" class="uk-icon-image uk-icon-link" uk-toggle="target: #chatbox; animation: uk-animation-fade" style="
background-image: url(<%= image_url("cross.svg") %>); color: rgba(255, 255, 255, 0);;">
 -----
</a>



  <div id="groups">
    <!-- <span>Group chats:</span> -->
    <div>
        <ul uk-tab>
      <% @grid.group_chats.each do |group| %>
        <!-- <a href="" class="group" data-id="<%= group.id %>"><%= group.name %></a> -->
          <li><a href="#"><%= group.name %></a></li>
          <% end %>
        </ul>


    </div>
  </div>

  <div id ="messages">
    <% @grid.group_chats.first.messages.each do |message| %>
      <span><b><%= "#{message.user.email}:" %></b> <%= "#{message.content}" %></span>
      <br>
      <br>
    <% end %>
  </div>

  <div id="chat-input">
    <div class="uk-margin">
        <div class="uk-inline">
          <span class="uk-form-icon uk-form-icon-flip uk-icon-image" style="background-image: url(<%= image_url("chevron-right.svg") %>);"></span>

            <input class="uk-input" type="text">
        </div>
    </div>
  </div>
</div>

app/views/shared/_dashboard.html.erb
<!-- This file should be reworked, it's messy and inefficient -->
<div id="offcanvas-flip-dashboard" uk-offcanvas="flip: true; overlay: true">
  <div class="uk-offcanvas-bar">
    <button class="uk-offcanvas-close" type="button" uk-close></button>
    <% if current_user %>
      <h2>Pixels:
        <%= current_user.pixel_credits %>
      </h2>
      <h4>Add Pixels</h4>
      <div id="buy-btn-container">
        <button class="uk-button uk-button-default" onClick='document.getElementById("amount").value = 10'>10</button>
        <button class="uk-button uk-button-default" onClick='document.getElementById("amount").value = 50'>50</button>
        <button class="uk-button uk-button-default" onClick='document.getElementById("amount").value = 100'>100</button>
        <button class="uk-button uk-button-default" onClick='document.getElementById("amount").value = 200'>200</button>
      </div>
      <div id="buy-form">
        <%= form_tag orders_path do %>
          <%= hidden_field_tag 'user_id', current_user[:id] %>
          <div uk-tooltip="title: Or enter a custom amount.; pos: left">
            <%= number_field_tag 'amount', '10',  class: "uk-input", placeholder: "Custom Amount", inputmode: "decimal" %>
          </div>
          <br>
           <!-- # <%= hidden_field_tag 'price', price = 10 %>  should be outright removed-->
          <%= submit_tag 'Donate!', class: 'uk-button uk-button-primary', style: "width:100%; border-radius: 0;" %>

        <% end %>
      </div>
      <h3>Donation History</h3>
      <% if @show %>
        <% if @orders.count > 0 %>
          <div id="past-orders">
            <br>
            <table class="uk-table uk-table-divider">
              <thead>
                <tr>
                  <th>Paid</th>
                  <th>Pixels</th>
                  <th>Date</th>
                  <th>ID</th>
                </tr>
              </thead>
              <tbody>
                <% @orders.each do |order| %>
                  <tr>
                    <td>
                      <%= number_to_currency(order.price, :unit=>'€') %>
                    </td>
                    <td>
                      <%= order.amount %>
                    </td>
                    <td uk-tooltip="title:at <%= order.created_at.to_s[11..15] %> ; pos: right">
                      <%= order.created_at.to_s[0..9] %>
                    </td>
                    <td>
                      <%= order.id %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% else %>
          <br>
          <center>
            <p style="color: #b3b3b3;">No donations yet :(</p>
          </center>
        <% end %>
      <% end %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "uk-button uk-button-primary", id: "logout" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button class="uk-icon uk-close close" data-dismiss="alert" aria-label="Close">
      <span><svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" data-svg="close-icon"><line fill="none" stroke="#000" stroke-width="1.1" x1="1" y1="1" x2="13" y2="13"></line><line fill="none" stroke="#000" stroke-width="1.1" x1="13" y1="1" x2="1" y2="13"></line></svg></span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button class="uk-icon uk-close close" data-dismiss="alert" aria-label="Close">
      <span><svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" data-svg="close-icon"><line fill="none" stroke="#000" stroke-width="1.1" x1="1" y1="1" x2="13" y2="13"></line><line fill="none" stroke="#000" stroke-width="1.1" x1="13" y1="1" x2="1" y2="13"></line></svg></span>
    </button>
  </div>
<% end %>



<!-- <button class="close" data-dismiss="alert" aria-label="Close"><svg width="14" height="14" viewBox="0 0 14 14" xmlns="http://www.w3.org/2000/svg" data-svg="close-icon"><line fill="none" stroke="#000" stroke-width="1.1" x1="1" y1="1" x2="13" y2="13"></line><line fill="none" stroke="#000" stroke-width="1.1" x1="13" y1="1" x2="1" y2="13"></line></svg></button> -->

app/views/shared/_navbar.html.erb
<nav class="navbar">

    <div class="navbar-left">

      <div class="navbar-logo">
        <%= link_to "/" do %>
          <%= image_tag('logo.png')  %>
        <% end %>
      </div>

      <% if (user_signed_in?) %>

      <div class="user-count">
        <img src="<%= image_path("online.svg") %>">
        <span id="user-count">1</span> <span id="user-online">currently online</span>
      </div>

      <div class="user-count-mobile" uk-tooltip="title: Users online & your pixels.; pos: bottom">
          <li>
          <img src="<%= image_path("online.svg") %>">
          <span id="user-count-m">1</span> <span id="user-online"></span>
          </li>
          <li>
          <img src="<%= image_path("grid.svg") %>">
          <span class="credits"><%= current_user.pixel_credits %></span>
          </li>
      </div>

      <% end %>

    </div>

    </div>

    <div class="navbar-right">

        <% if (user_signed_in?) %>

          <% if current_user.admin %>

          <div>
            <span class="credits credits-desktop">Pixels: <%= current_user.pixel_credits %></span>
          </div>
          <div>
            <button id="dashboard" class="uk-button uk-button-default" type="button" uk-toggle="target: #offcanvas-flip-dashboard">Add Pixels</button>
          </div>

        <% end %>

        <div uk-tooltip="title: Profile coming soon!; pos: bottom">
          <%= image_tag "logo.png", class: "avatar", id: "navbarDropdown"%>
        </div>

              <% else %>
        <div>
          <button id="dashboard" class="uk-button uk-button-primary" type="button" uk-toggle="target: #offcanvas-flip-signin">Get Started</button>
        </div>
      <% end %>
  </div>
<%= render 'shared/sign_in' %>
</nav>

app/views/shared/_sign_in.html.erb
<div id="offcanvas-flip-signin" uk-offcanvas="flip: true; overlay: true">
    <div class="uk-offcanvas-bar">
        <button class="uk-offcanvas-close" type="button" uk-close></button>
        <h3>Sign Up</h3>
        <%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
        <%= f.email_field :email, class: "uk-input", placeholder: "Email" %>
        <%= f.text_field :username, class: "uk-input", placeholder: "Username" %>
        <%= f.password_field :password, class: "uk-input", placeholder: "Password" %>
        <%= f.password_field :password_confirmation, class: "uk-input", placeholder: "Confirm password" %>
        <%= f.submit "Sign up", class: "uk-button uk-button-primary", style: "width: 100%; background: #dee2e6; margin-bottom: 12px; margin: 6px 0px 0px 0px;" %>
        <% end %>
        <br>
        <center>
            <h5>Or</h5>
        </center>
        <h3>Sign In</h3>
        <%= simple_form_for(:user, :url => session_path(:user)) do |f| %>
        <%= f.text_field :email, class: "uk-input", placeholder: "Email" %>
        <%= f.password_field :password, class: "uk-input", placeholder: "Password" %>
        <br>
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
        <%= f.submit 'Sign in', class: "uk-button uk-button-primary", style: "width: 100%; background: #dee2e6; margin-bottom: 12px;" %>
        <br>
        <%= link_to "Forgot your password?", new_password_path(:user) %>
        <% end %>
    </div>
</div>